name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make dist
      run: make dist
    - uses: actions/upload-artifact@v1
      with:
        name: gofish-1.0.tar.gz
        path: ./gofish-1.0.tar.gz
